@startuml
'https://plantuml.com/use-case-diagram

skinparam actorStyle awesome


User --> (Start Menu)
(Start Menu) --> (Play Game)
(Start Menu) -right-> (Settings)
(Start Menu) --> (Leaderboards)
(Start Menu) --> (Exit Game)

(Play Game) --> (Choose Level)
(Choose Level) --> (Choose Difficulty)
(Choose Difficulty) --> (Playing the Game)
(Playing the Game) --> (Start Menu)
(Playing the Game) -right-> (Exit Game)
(Playing the Game) -up-> (Settings)
(Settings) --> (Playing the Game)

(Leaderboards) --> (Start Menu)
(Settings) -right-> (Start Menu)


(Start Menu)
(Play Game)
(Settings)
(Leaderboards)
(Exit Game)
(Playing the Game)

@enduml